/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface EmailSequenceData {
	[k: string]: unknown;
}

export interface EmailSequenceContractDefinition
	extends ContractDefinition<EmailSequenceData> {}

export interface EmailSequenceContract extends Contract<EmailSequenceData> {}
