/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface OutreachAccountData {
	mirrors?: string[];
	[k: string]: unknown;
}

export interface OutreachAccountContractDefinition
	extends ContractDefinition<OutreachAccountData> {}

export interface OutreachAccountContract
	extends Contract<OutreachAccountData> {}
