version: '2.1'

services:
  sut:
    image: balena/jellyfish-sut:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    secrets:
      - integration_outreach_app_id
      - integration_outreach_app_secret
      - integration_outreach_signature_key
    networks:
      - internal

secrets:
  integration_outreach_app_id:
    file: ./.balena/secrets/integration_outreach_app_id.txt
  integration_outreach_app_secret:
    file: ./.balena/secrets/integration_outreach_app_secret.txt
  integration_outreach_signature_key:
    file: ./.balena/secrets/integration_outreach_signature_key.txt
